import frappe
from frappe import _
from frappe.utils import flt, add_days


PR_READY_QTY_FIELD = "custom_before_dispatch_ready_qty"
PE_READY_QTY_FIELD = "custom_before_dispatch_ready_qty"


def execute(filters=None):
    filters = filters or {}
    data = get_data(filters)
    max_entries = 0
    for row in data:
        for key in row:
            if key.startswith("bd_pr_"):
                max_entries = max(max_entries, int(key.rsplit("_", 1)[1]))
    return get_columns(max_entries), data


def get_columns(max_entries=0):
    columns = [
        {"label": _("Purchase Order / Item"), "fieldname": "name", "fieldtype": "Data", "width": 220},
        {"label": _("PO Date"), "fieldname": "po_date", "fieldtype": "Date", "width": 110},
        {"label": _("Vendor Name"), "fieldname": "supplier_name", "fieldtype": "Data", "width": 200},
        {"label": _("Item Code"), "fieldname": "item_code", "fieldtype": "Link", "options": "Item", "width": 130},
        {"label": _("Item Name"), "fieldname": "item_name", "fieldtype": "Data", "width": 220},
        {"label": _("Delivery Date"), "fieldname": "required_by", "fieldtype": "Date", "width": 110},
        {"label": _("Dispatch Date"), "fieldname": "dispatch_date", "fieldtype": "Date", "width": 110},
        {"label": _("Rate"), "fieldname": "rate", "fieldtype": "Currency", "width": 110},
        {"label": _("Qty"), "fieldname": "qty", "fieldtype": "Float", "width": 90},
        {"label": _("Amount"), "fieldname": "amount", "fieldtype": "Currency", "width": 130},
        {"label": _("Taxes"), "fieldname": "taxes", "fieldtype": "Currency", "width": 120},
        {"label": _("Total Amount"), "fieldname": "total_amount", "fieldtype": "Currency", "width": 130},
        {"label": _("Advance %"), "fieldname": "advance_percent", "fieldtype": "Percent", "width": 100},
        {"label": _("Advance Amount"), "fieldname": "advance_amount", "fieldtype": "Currency", "width": 130},
        {"label": _("Advance Paid Value"), "fieldname": "advance_paid", "fieldtype": "Currency", "width": 140},
        {"label": _("Payment Request Date"), "fieldname": "payment_request_date", "fieldtype": "Date", "width": 130},
        {"label": _("Advance Paid Date"), "fieldname": "advance_paid_date", "fieldtype": "Date", "width": 130},
        {"label": _("Before Dispatch %"), "fieldname": "bd_percent", "fieldtype": "Percent", "width": 120},
        {"label": _("Total Dispatch Ready Qty"), "fieldname": "bd_ready_qty", "fieldtype": "Float", "width": 150},
        {"label": _("Pending Qty To Receive"), "fieldname": "pending_qty", "fieldtype": "Float", "width": 140},
        {"label": _("Before Dispatch Amount To Be Paid"), "fieldname": "bd_amount", "fieldtype": "Currency", "width": 180},
        {"label": _("Before Dispatch Amount Paid"), "fieldname": "bd_paid", "fieldtype": "Currency", "width": 160},
        {"label": _("Payment Request Generated by Purchase Date"), "fieldname": "bd_request_generated", "fieldtype": "Data", "width": 200},
        {"label": _("Actual Dispatch Date"), "fieldname": "actual_dispatch_date", "fieldtype": "Date", "width": 130},
        # ---- On Delivery (before After Delivery) ----
        {"label": _("On Delivery Payment Term"), "fieldname": "od_term", "fieldtype": "Data", "width": 200},
        {"label": _("On Delivery Payment Due Date"), "fieldname": "od_due_date", "fieldtype": "Date", "width": 170},
        {"label": _("On Delivery Amount To Be Paid"), "fieldname": "od_amount", "fieldtype": "Currency", "width": 180},
        {"label": _("On Delivery Paid Amount"), "fieldname": "od_paid", "fieldtype": "Currency", "width": 160},
        {"label": _("On Delivery Payment Request Date"), "fieldname": "od_request_date", "fieldtype": "Date", "width": 200},
        {"label": _("On Delivery Payment Date"), "fieldname": "od_paid_date", "fieldtype": "Date", "width": 170},
        # ---- After Delivery ----
        {"label": _("After Delivery Payment Term"), "fieldname": "ad_term", "fieldtype": "Data", "width": 230},
        {"label": _("Credit Days"), "fieldname": "credit_days", "fieldtype": "Int", "width": 100},
        {"label": _("Actual GRN Date"), "fieldname": "actual_grn_date", "fieldtype": "Date", "width": 130},
        {"label": _("After Delivery Payment Due Date"), "fieldname": "ad_due_date", "fieldtype": "Date", "width": 170},
        # {"label": _("Quality Status"), "fieldname": "quality_status", "fieldtype": "Data", "width": 120},
        {"label": _("Actual Received Qty"), "fieldname": "actual_received_qty", "fieldtype": "Float", "width": 140},
        {"label": _("Pending Qty"), "fieldname": "ad_pending_qty", "fieldtype": "Float", "width": 110},
        {"label": _("After Delivery Amount To Be Paid"), "fieldname": "ad_amount", "fieldtype": "Currency", "width": 180},
        {"label": _("After Delivery Paid Amount"), "fieldname": "ad_paid", "fieldtype": "Currency", "width": 160},
        {"label": _("After Delivery Payment Request Date"), "fieldname": "ad_request_date", "fieldtype": "Date", "width": 200},
        {"label": _("After Delivery Payment Date"), "fieldname": "ad_paid_date", "fieldtype": "Date", "width": 170},
    ]

    # One Payment Request + ready qty column pair per Before Dispatch Payment Request,
    # placed right after the total "Before Dispatch Ready Qty" column.
    entry_columns = []
    for n in range(1, max_entries + 1):
        entry_columns.append({
            "label": _("Before Dispatch Payment Request {0}").format(n),
            "fieldname": "bd_pr_{0}".format(n),
            "fieldtype": "Link",
            "options": "Payment Request",
            "width": 170,
        })
        entry_columns.append({
            "label": _("Before Dispatch Ready Qty {0}").format(n),
            "fieldname": "bd_qty_{0}".format(n),
            "fieldtype": "Float",
            "width": 150,
        })
    at = [c["fieldname"] for c in columns].index("bd_ready_qty") + 1
    return columns[:at] + entry_columns + columns[at:]


def norm_term(value):
    """Normalise a payment term name (collapse repeated spaces) for comparison."""
    return " ".join((value or "").split())


def field_select(doctype, fieldname, alias_prefix):
    """Returns 'alias.`field`' if the column exists, otherwise NULL."""
    if fieldname and frappe.db.has_column(doctype, fieldname):
        return "{0}.`{1}`".format(alias_prefix, fieldname)
    return "NULL"


def get_pi_po_map(po_names):
    """
    Returns {purchase_invoice: set(purchase_order)} for submitted Purchase Invoices
    whose items link to the given POs.
    """
    if not po_names:
        return {}

    pi_rows = frappe.db.sql(
        """
        SELECT DISTINCT pii.parent AS purchase_invoice, pii.purchase_order
        FROM `tabPurchase Invoice Item` pii
        INNER JOIN `tabPurchase Invoice` pinv ON pinv.name = pii.parent
        WHERE pinv.docstatus = 1
            AND pii.purchase_order IN %(pos)s
        """,
        {"pos": tuple(po_names)},
        as_dict=True,
    )
    pi_to_pos = {}
    for r in pi_rows:
        pi_to_pos.setdefault(r.purchase_invoice, set()).add(r.purchase_order)
    return pi_to_pos


def get_payment_request_item_ready_qty(pr_names):
    """
    Returns {payment_request_name: {item_code: before_dispatch_ready_qty}} from the
    Payment Request child table `custom_items` (doctype "Payment Request CT").
    """
    if not pr_names:
        return {}

    rows = frappe.db.sql(
        """
        SELECT parent, item_code, before_dispatch_ready_qty
        FROM `tabPayment Request CT`
        WHERE parenttype = 'Payment Request'
            AND parent IN %(prs)s
        """,
        {"prs": tuple(pr_names)},
        as_dict=True,
    )

    result = {}
    for r in rows:
        if not r.item_code:
            continue
        items = result.setdefault(r.parent, {})
        items[r.item_code] = items.get(r.item_code, 0) + flt(r.before_dispatch_ready_qty)
    return result


def get_payment_entry_rows(po_names, pi_to_pos=None):
    """
    Returns a list of Payment Entry allocations that belong to the given POs, as dicts:
    purchase_order, payment_request, payment_term, pe_term, pe_ready_qty,
    reference_no, allocated_amount, posting_date.

    Sources:
      1. Payment Entry Reference rows against the Purchase Order itself.
      2. Payment Entry Reference rows against Purchase Invoices whose items link
         to the PO. When a Purchase Invoice pulls in an advance, ERPNext moves
         the allocation from the PO row to a Purchase Invoice row. Payments made
         directly against the Purchase Invoice (e.g. After Delivery) are also here.
    """
    if not po_names:
        return []

    if frappe.db.has_column("Payment Entry", "custom_payment_term"):
        pe_term_select = "pe.custom_payment_term"
    else:
        pe_term_select = "NULL"

    pe_ready_select = field_select("Payment Entry", PE_READY_QTY_FIELD, "pe")

    select_sql = """
        SELECT
            per.reference_name AS reference_name,
            per.payment_request,
            per.payment_term,
            per.allocated_amount,
            pe.posting_date,
            pe.unallocated_amount AS unallocated_amount,
            pe.total_allocated_amount AS total_allocated_amount,
            pe.reference_no AS reference_no,
            {pe_term_select} AS pe_term,
            {pe_ready_select} AS pe_ready_qty
        FROM `tabPayment Entry Reference` per
        INNER JOIN `tabPayment Entry` pe ON pe.name = per.parent
        WHERE pe.docstatus = 1
            AND per.reference_doctype = %(doctype)s
            AND per.reference_name IN %(names)s
    """.format(pe_term_select=pe_term_select, pe_ready_select=pe_ready_select)

    result = []

    # 1. Rows against the Purchase Order
    for e in frappe.db.sql(
        select_sql,
        {"doctype": "Purchase Order", "names": tuple(po_names)},
        as_dict=True,
    ):
        e["purchase_order"] = e.reference_name
        e["pi_pos"] = set()
        result.append(e)

    # 2. Rows against Purchase Invoices linked to these POs
    if pi_to_pos is None:
        pi_to_pos = get_pi_po_map(po_names)

    if pi_to_pos:
        for e in frappe.db.sql(
            select_sql,
            {"doctype": "Purchase Invoice", "names": tuple(pi_to_pos.keys())},
            as_dict=True,
        ):
            e["pi_pos"] = pi_to_pos.get(e.reference_name, set())
            e["purchase_order"] = None
            result.append(e)

    # A Payment Entry can pay more than the PO outstanding; the excess stays as
    # "unallocated". Add it back (pro rata over its reference rows) so the report
    # shows the full amount paid against the payment term.
    for e in result:
        if flt(e.unallocated_amount) > 0 and flt(e.total_allocated_amount) > 0:
            e["allocated_amount"] = flt(e.allocated_amount) + flt(e.unallocated_amount) * (
                flt(e.allocated_amount) / flt(e.total_allocated_amount)
            )

    return result


def get_term_details(po_names, term_like):
    """
    Returns {po_name: {"percent", "amount", "paid", "request_date", "paid_date",
                       "payment_term", "credit_days", "ready_qty", "ready_items",
                       "ready_entries"}}
    for Payment Schedule rows whose payment term matches term_like
    (e.g. "%Advance%", "%Before Dispatch%", "%After Delivery%", "%On Delivery%").

    Payment Requests can be raised against the Purchase Order OR against a
    Purchase Invoice linked to the PO. Payment Entries can likewise pay against
    either. Each submitted Payment Entry reference row is assigned to a term in
    this order:
      1. the Payment Request's Payment Reference rows (explicit schedule link)
      2. Payment Entry Reference.payment_term
      3. Payment Entry.custom_payment_term (header)
      4. Payment Request.custom_payment_term
    The Payment Request is Payment Entry Reference.payment_request, or, when that
    is empty, the Payment Entry's reference_no if it is a Payment Request name.
    Paid is capped at the schedule amount and falls back to the schedule's
    paid_amount when that is higher.

    request_date = earliest submitted Payment Request date for those rows
                   (including requests that received a payment for the term).
    paid_date    = latest Payment Entry posting date for those rows.
    ready_items  = {item_code: before_dispatch_ready_qty summed over all matched
                   Payment Requests}, from the Payment Request child table.
    ready_entries = [{"name", "request_date", "items": {item_code: qty}}, ...], one
                   per matched Payment Request that has child rows (oldest first).
    ready_qty    = total of ready_items. When no matched Payment Request has child
                   rows, falls back to the header ready qty field of the latest
                   matched Payment Request, else of the latest matched Payment Entry.
    """
    if not po_names:
        return {}

    schedule_rows = frappe.db.sql(
        """
        SELECT
            ps.name AS schedule_name,
            ps.parent AS purchase_order,
            ps.payment_term,
            ps.credit_days,
            ps.invoice_portion,
            ps.payment_amount,
            ps.paid_amount
        FROM `tabPayment Schedule` ps
        WHERE ps.parenttype = 'Purchase Order'
            AND ps.parent IN %(pos)s
            AND ps.payment_term LIKE %(term)s
        """,
        {"pos": tuple(po_names), "term": term_like},
        as_dict=True,
    )
    if not schedule_rows:
        return {}

    schedule_names = {r.schedule_name for r in schedule_rows}
    term_keys = {(r.purchase_order, norm_term(r.payment_term)) for r in schedule_rows}
    term_pos = {po for po, _t in term_keys}

    # Purchase Invoices linked to these POs
    pi_to_pos = get_pi_po_map(po_names)

    # Payment Requests raised against these POs or against their Purchase Invoices
    pr_ready_select = field_select("Payment Request", PR_READY_QTY_FIELD, "pr")
    pr_rows = frappe.db.sql(
        """
        SELECT
            pr.name,
            pr.reference_doctype,
            pr.reference_name,
            pr.custom_payment_term AS payment_term,
            COALESCE(pr.transaction_date, DATE(pr.creation)) AS request_date,
            {pr_ready_select} AS ready_qty
        FROM `tabPayment Request` pr
        WHERE pr.docstatus = 1
            AND (
                (pr.reference_doctype = 'Purchase Order'
                    AND pr.reference_name IN %(pos)s)
                OR
                (pr.reference_doctype = 'Purchase Invoice'
                    AND pr.reference_name IN %(pis)s)
            )
        """.format(pr_ready_select=pr_ready_select),
        {
            "pos": tuple(po_names),
            "pis": tuple(pi_to_pos.keys()) or ("",),
        },
        as_dict=True,
    )

    # payment request -> set of POs it belongs to (directly, or through its PI)
    pr_pos = {}
    for pr in pr_rows:
        if pr.reference_doctype == "Purchase Order":
            pr_pos[pr.name] = {pr.reference_name}
        else:
            pr_pos[pr.name] = set(pi_to_pos.get(pr.reference_name, set()))

    pr_date = {pr.name: pr.request_date for pr in pr_rows}

    pref_map = {}
    pr_item_ready = {}  # payment request -> {item_code: ready qty}
    if pr_rows:
        pr_names = tuple(r.name for r in pr_rows)
        pref_rows = frappe.db.sql(
            """
            SELECT parent, payment_schedule
            FROM `tabPayment Reference`
            WHERE parenttype = 'Payment Request'
                AND parent IN %(prs)s
            """,
            {"prs": pr_names},
            as_dict=True,
        )
        for p in pref_rows:
            if p.payment_schedule:
                pref_map.setdefault(p.parent, set()).add(p.payment_schedule)

        pr_item_ready = get_payment_request_item_ready_qty(pr_names)

    # Payment Requests that belong to this term (by schedule link or by custom term)
    matched_prs = set()
    term_pr_names = set()  # PRs matched only by their custom_payment_term
    for pr in pr_rows:
        linked = pref_map.get(pr.name, set()) & schedule_names
        by_term = any(
            (po, norm_term(pr.payment_term)) in term_keys
            for po in pr_pos.get(pr.name, set())
        )
        if linked:
            matched_prs.add(pr.name)
        elif by_term and not pref_map.get(pr.name):
            matched_prs.add(pr.name)
            term_pr_names.add(pr.name)

    # Payment Entry allocations (against the PO or its Purchase Invoices)
    per_rows = get_payment_entry_rows(po_names, pi_to_pos)

    paid_by_po = {}
    paid_date_by_po = {}
    pe_ready_by_po = {}  # po -> (posting_date, ready_qty) of latest matched Payment Entry
    for e in per_rows:
        pr_name = e.payment_request
        if not pr_name and e.reference_no in pr_date:
            pr_name = e.reference_no

        # resolve which PO this allocation belongs to
        po = e.purchase_order
        if not po:
            pi_pos = e.get("pi_pos") or set()
            req_pos = (pr_pos.get(pr_name, set()) & pi_pos) if pr_name else set()
            if len(req_pos) == 1:
                po = next(iter(req_pos))
            elif len(pi_pos) == 1:
                po = next(iter(pi_pos))
        if not po or po not in po_names:
            continue

        linked_schedules = pref_map.get(pr_name, set()) if pr_name else set()

        if linked_schedules:
            hit = bool(linked_schedules & schedule_names)
        elif norm_term(e.payment_term):
            hit = (po, norm_term(e.payment_term)) in term_keys
        elif norm_term(e.pe_term):
            hit = (po, norm_term(e.pe_term)) in term_keys
        elif pr_name:
            hit = pr_name in term_pr_names
        else:
            hit = False

        if not hit:
            continue

        # the request that received this payment also counts for the term's request date
        if pr_name and pr_name in pr_date:
            matched_prs.add(pr_name)
            # make sure the request is attributed to the PO this payment resolved to
            pr_pos.setdefault(pr_name, set()).add(po)

        paid_by_po[po] = paid_by_po.get(po, 0) + flt(e.allocated_amount)
        if flt(e.allocated_amount) > 0:
            cur = paid_date_by_po.get(po)
            if e.posting_date and (not cur or e.posting_date > cur):
                paid_date_by_po[po] = e.posting_date

        if e.pe_ready_qty is not None:
            cur_ready = pe_ready_by_po.get(po)
            if not cur_ready or (e.posting_date and (not cur_ready[0] or e.posting_date > cur_ready[0])):
                pe_ready_by_po[po] = (e.posting_date, flt(e.pe_ready_qty))

    # earliest request date, ready qty per item and header ready qty per PO
    # for the matched Payment Requests
    request_dates = {}
    pr_ready_by_po = {}  # po -> (request_date, ready_qty) from the PR header field
    ready_items_by_po = {}  # po -> {item_code: ready qty summed over matched PRs}
    ready_entries_by_po = {}  # po -> [one entry per matched PR with child rows]
    for pr in pr_rows:
        if pr.name not in matched_prs:
            continue
        pr_items = pr_item_ready.get(pr.name, {})
        for po in pr_pos.get(pr.name, set()) & term_pos:
            if pr.request_date:
                cur = request_dates.get(po)
                if not cur or pr.request_date < cur:
                    request_dates[po] = pr.request_date
            if pr.ready_qty is not None:
                cur_ready = pr_ready_by_po.get(po)
                if not cur_ready or (pr.request_date and (not cur_ready[0] or pr.request_date > cur_ready[0])):
                    pr_ready_by_po[po] = (pr.request_date, flt(pr.ready_qty))
            if pr_items:
                ready_entries_by_po.setdefault(po, []).append(
                    {"name": pr.name, "request_date": pr.request_date, "items": pr_items}
                )
            for item_code, qty in pr_items.items():
                items = ready_items_by_po.setdefault(po, {})
                items[item_code] = items.get(item_code, 0) + qty

    details = {}
    for r in schedule_rows:
        d = details.setdefault(
            r.purchase_order,
            {"percent": 0, "amount": 0, "paid": 0, "schedule_paid": 0,
             "request_date": None, "paid_date": None,
             "terms": [], "credit_days": 0, "ready_qty": None, "ready_items": {},
             "ready_entries": []},
        )
        d["percent"] += flt(r.invoice_portion)
        d["amount"] += flt(r.payment_amount)
        d["schedule_paid"] += flt(r.paid_amount)
        if r.payment_term and r.payment_term not in d["terms"]:
            d["terms"].append(r.payment_term)
        d["credit_days"] = max(d["credit_days"], int(flt(r.credit_days)))

    for po, d in details.items():
        paid = max(paid_by_po.get(po, 0), d["schedule_paid"])
        # show the actual paid amount, even when it is more than the schedule amount
        d["paid"] = paid
        d["request_date"] = request_dates.get(po)
        d["paid_date"] = paid_date_by_po.get(po) if paid > 0 else None
        d["payment_term"] = ", ".join(d["terms"])
        if po in ready_items_by_po:
            d["ready_items"] = ready_items_by_po[po]
            d["ready_entries"] = sorted(
                ready_entries_by_po.get(po, []),
                key=lambda e: (str(e["request_date"] or ""), e["name"]),
            )
            d["ready_qty"] = sum(ready_items_by_po[po].values())
        elif po in pr_ready_by_po:
            d["ready_qty"] = pr_ready_by_po[po][1]
        elif po in pe_ready_by_po:
            d["ready_qty"] = pe_ready_by_po[po][1]

    return details


def get_item_taxes(po_names):
    """Returns {item_row_name: total tax amount} from Item Wise Tax Detail."""
    if not po_names:
        return {}

    rows = frappe.db.sql(
        """
        SELECT item_row, SUM(amount) AS tax
        FROM `tabItem Wise Tax Detail`
        WHERE parenttype = 'Purchase Order'
            AND parent IN %(pos)s
        GROUP BY item_row
        """,
        {"pos": tuple(po_names)},
        as_dict=True,
    )
    return {r.item_row: flt(r.tax) for r in rows}


def get_grn_details(po_names):
    """
    Returns {po_item_row_name: {"grn_date", "quality_status"}} from submitted,
    non-return Purchase Receipts.

    grn_date       = latest Purchase Receipt posting date for the PO item.
    quality_status = Rejected > Pending > Accepted across the receipt rows, where
                     Pending = item requires inspection but no Quality Inspection
                     is linked on the Purchase Receipt Item. Blank if the item
                     needs no inspection and none is linked.
    """
    if not po_names:
        return {}

    rows = frappe.db.sql(
        """
        SELECT
            pri.purchase_order_item AS row_name,
            pr.posting_date AS posting_date,
            pri.quality_inspection AS quality_inspection,
            qi.status AS qi_status,
            it.inspection_required_before_purchase AS qi_required
        FROM `tabPurchase Receipt Item` pri
        INNER JOIN `tabPurchase Receipt` pr ON pr.name = pri.parent
        LEFT JOIN `tabQuality Inspection` qi ON qi.name = pri.quality_inspection
        LEFT JOIN `tabItem` it ON it.name = pri.item_code
        WHERE pr.docstatus = 1
            AND pr.is_return = 0
            AND pri.purchase_order IN %(pos)s
        """,
        {"pos": tuple(po_names)},
        as_dict=True,
    )

    result = {}
    for r in rows:
        d = result.setdefault(r.row_name, {"grn_date": None, "statuses": set()})
        if r.posting_date and (not d["grn_date"] or r.posting_date > d["grn_date"]):
            d["grn_date"] = r.posting_date
        if r.qi_status:
            d["statuses"].add(r.qi_status)
        elif r.qi_required:
            d["statuses"].add("Pending")

    for d in result.values():
        d["quality_status"] = combine_quality(d["statuses"])
    return result


def combine_quality(statuses):
    statuses = {s for s in statuses if s}
    if not statuses:
        return None
    if "Rejected" in statuses:
        return "Rejected"
    if "Pending" in statuses:
        return "Pending"
    return "Accepted"


def get_data(filters):
    conditions = ["po.docstatus = 1"]
    values = {}

    if filters.get("company"):
        conditions.append("po.company = %(company)s")
        values["company"] = filters["company"]

    if filters.get("supplier"):
        conditions.append("po.supplier = %(supplier)s")
        values["supplier"] = filters["supplier"]

    if filters.get("purchase_order"):
        conditions.append("po.name = %(purchase_order)s")
        values["purchase_order"] = filters["purchase_order"]

    if filters.get("item_code"):
        conditions.append("poi.item_code = %(item_code)s")
        values["item_code"] = filters["item_code"]

    if filters.get("from_date"):
        conditions.append("poi.schedule_date >= %(from_date)s")
        values["from_date"] = filters["from_date"]

    if filters.get("to_date"):
        conditions.append("poi.schedule_date <= %(to_date)s")
        values["to_date"] = filters["to_date"]

    rows = frappe.db.sql(
        """
        SELECT
            po.name AS purchase_order,
            po.supplier_name AS supplier_name,
            po.transaction_date AS po_date,
            po.schedule_date AS po_schedule_date,
            po.grand_total AS po_grand_total,
            po.rounded_total AS po_rounded_total,
            po.total_taxes_and_charges AS po_taxes,
            poi.item_code AS item_code,
            poi.item_name AS item_name,
            poi.schedule_date AS item_schedule_date,
            poi.expected_delivery_date AS dispatch_date,
            poi.rate AS rate,
            poi.qty AS qty,
            poi.received_qty AS received_qty,
            poi.amount AS amount
        FROM `tabPurchase Order` po
        INNER JOIN `tabPurchase Order Item` poi ON poi.parent = po.name
        WHERE {conditions}
        ORDER BY po.transaction_date DESC, po.name, poi.idx
        """.format(conditions=" AND ".join(conditions)),
        values,
        as_dict=True,
    )

    # Group items under their Purchase Order
    grouped = {}
    for r in rows:
        grouped.setdefault(r.purchase_order, []).append(r)

    po_list = list(grouped.keys())
    advances = get_term_details(po_list, "%Advance%")
    before_dispatch = get_term_details(po_list, "%Before Dispatch%")
    after_delivery = get_term_details(po_list, "%After Delivery%")
    on_delivery = get_term_details(po_list, "%On Delivery%")
    item_taxes = get_item_taxes(po_list)
    grn_details = get_grn_details(po_list)

    data = []
    for po, items in grouped.items():
        po_amount = sum(flt(i.amount) for i in items)
        po_qty = sum(flt(i.qty) for i in items)
        po_received_qty = sum(flt(i.received_qty) for i in items)
        po_pending_qty = sum(max(flt(i.qty) - flt(i.received_qty), 0) for i in items)

        # Actual dispatch date = expected_delivery_date of the item rows
        # (PO row shows the earliest item date)
        item_dispatch_dates = [i.dispatch_date for i in items if i.dispatch_date]
        po_actual_dispatch = min(item_dispatch_dates) if item_dispatch_dates else None

        adv = advances.get(po, {})
        bd = before_dispatch.get(po, {})
        ad = after_delivery.get(po, {})
        od = on_delivery.get(po, {})
        ad_credit_days = int(ad.get("credit_days") or 0)

        # PO level GRN date (latest) and quality status
        po_grn_dates = [
            grn_details[i.row_name]["grn_date"]
            for i in items
            if i.row_name in grn_details and grn_details[i.row_name]["grn_date"]
        ]
        po_grn_date = max(po_grn_dates) if po_grn_dates else None
        po_ad_due_date = (
            add_days(po_grn_date, ad_credit_days) if (po_grn_date and ad) else None
        )
        # On Delivery payment due date = Actual GRN Date
        po_od_due_date = po_grn_date
        po_quality = combine_quality(
            {grn_details[i.row_name]["quality_status"] for i in items if i.row_name in grn_details}
        )

        # Yes / No: has a Payment Request been raised for the Before Dispatch term
        # (blank when the PO has no Before Dispatch term)
        bd_request_generated = (
            ("Yes" if bd.get("request_date") else "No") if bd else None
        )

        grand_total = flt(items[0].po_grand_total)
        # payment schedule is calculated on rounded_total
        po_total = flt(items[0].po_rounded_total) or grand_total
        rounding_diff = po_total - grand_total
        po_taxes = flt(items[0].po_taxes)

        # If item wise tax rows are not available, spread the PO tax total over
        # the items by amount, so item totals always add up to the PO total.
        item_tax_found = sum(flt(item_taxes.get(i.row_name, 0)) for i in items)
        spread_po_taxes = (not item_tax_found) and po_taxes and po_amount

        # Parent row (Purchase Order)
        data.append({
            "name": po,
            "parent_po": None,
            "indent": 0,
            "po_date": items[0].po_date,
            "supplier_name": items[0].supplier_name,
            "required_by": items[0].po_schedule_date,
            "qty": po_qty,
            "amount": po_amount,
            "taxes": po_taxes,
            "total_amount": po_total,
            "advance_percent": adv.get("percent"),
            "advance_amount": adv.get("amount"),
            "advance_paid": adv.get("paid"),
            "payment_request_date": adv.get("request_date"),
            "advance_paid_date": adv.get("paid_date"),
            "bd_percent": bd.get("percent"),
            # total of the item ready qtys from the Payment Requests (PO level)
            "bd_ready_qty": bd.get("ready_qty"),
            "pending_qty": po_pending_qty,
            "bd_amount": bd.get("amount"),
            "bd_paid": bd.get("paid"),
            "bd_request_generated": bd_request_generated,
            "actual_dispatch_date": po_actual_dispatch,
            "ad_term": ad.get("payment_term"),
            "credit_days": ad_credit_days if ad else None,
            "actual_grn_date": po_grn_date,
            "ad_due_date": po_ad_due_date,
            "quality_status": po_quality,
            "actual_received_qty": po_received_qty,
            "ad_pending_qty": po_pending_qty,
            "ad_amount": ad.get("amount"),
            "ad_paid": ad.get("paid"),
            "ad_request_date": ad.get("request_date"),
            "ad_paid_date": ad.get("paid_date"),
            "od_term": od.get("payment_term"),
            "od_due_date": po_od_due_date,
            "od_amount": od.get("amount"),
            "od_paid": od.get("paid"),
            "od_request_date": od.get("request_date"),
            "od_paid_date": od.get("paid_date"),
        })

        # Before Dispatch Payment Requests (oldest first) -> column number
        bd_entries = bd.get("ready_entries") or []
        bd_entry_no = {e["name"]: n for n, e in enumerate(bd_entries, 1)}
        for n, e in enumerate(bd_entries, 1):
            data[-1]["bd_pr_{0}".format(n)] = e["name"]
            data[-1]["bd_qty_{0}".format(n)] = sum(e["items"].values())

        # Child rows (Items) - percentages applied on the item's own total amount
        adv_percent = flt(adv.get("percent", 0))
        adv_paid_ratio = (
            flt(adv.get("paid", 0)) / flt(adv.get("amount", 0))
            if adv and flt(adv.get("amount", 0))
            else 0
        )

        bd_percent = flt(bd.get("percent", 0))
        bd_paid_ratio = (
            flt(bd.get("paid", 0)) / flt(bd.get("amount", 0))
            if bd and flt(bd.get("amount", 0))
            else 0
        )

        ad_percent = flt(ad.get("percent", 0))
        ad_paid_ratio = (
            flt(ad.get("paid", 0)) / flt(ad.get("amount", 0))
            if ad and flt(ad.get("amount", 0))
            else 0
        )

        od_percent = flt(od.get("percent", 0))
        od_paid_ratio = (
            flt(od.get("paid", 0)) / flt(od.get("amount", 0))
            if od and flt(od.get("amount", 0))
            else 0
        )

        # Ready qty per item code, split per Payment Request entry. If the same
        # item code is on several PO rows, the entries are shown on the first
        # row only, so the item rows still add up to the PO total.
        remaining_ready = {}
        for entry in bd.get("ready_entries") or []:
            for code, qty in entry["items"].items():
                remaining_ready.setdefault(code, []).append((entry["name"], qty))

        for i in items:
            if spread_po_taxes:
                item_tax = flt(po_taxes * flt(i.amount) / po_amount, 2)
            else:
                item_tax = flt(item_taxes.get(i.row_name, 0), 2)
            item_gross = flt(i.amount) + item_tax

            # spread the rounding difference so item totals add up to rounded_total
            item_rounding = (
                rounding_diff * item_gross / grand_total if grand_total else 0
            )
            item_total = flt(item_gross + item_rounding, 2)

            item_advance = flt(item_total * adv_percent / 100, 2)
            item_bd = flt(item_total * bd_percent / 100, 2)
            item_ad = flt(item_total * ad_percent / 100, 2)
            item_od = flt(item_total * od_percent / 100, 2)

            grn = grn_details.get(i.row_name, {})
            item_grn_date = grn.get("grn_date")
            item_pending = max(flt(i.qty) - flt(i.received_qty), 0)

            item_entries = remaining_ready.pop(i.item_code, []) if bd else []
            item_ready_qty = sum(q for _pr, q in item_entries) if item_entries else None

            data.append({
                "name": i.row_name,
                "parent_po": po,
                "indent": 1,
                "item_code": i.item_code,
                "item_name": i.item_name,
                "required_by": i.item_schedule_date,
                "dispatch_date": i.dispatch_date,
                "rate": i.rate,
                "qty": i.qty,
                "amount": i.amount,
                "taxes": item_tax,
                "total_amount": item_total,
                "advance_percent": adv.get("percent") if adv else None,
                "advance_amount": item_advance if adv else None,
                "advance_paid": flt(item_advance * adv_paid_ratio, 2) if adv else None,
                "payment_request_date": adv.get("request_date") if adv else None,
                "advance_paid_date": adv.get("paid_date") if adv else None,
                "bd_percent": bd.get("percent") if bd else None,
                # per item, from the Payment Request child table (custom_items)
                "bd_ready_qty": item_ready_qty,
                "pending_qty": item_pending,
                "bd_amount": item_bd if bd else None,
                "bd_paid": flt(item_bd * bd_paid_ratio, 2) if bd else None,
                "bd_request_generated": bd_request_generated,
                "actual_dispatch_date": i.dispatch_date,
                "ad_term": ad.get("payment_term") if ad else None,
                "credit_days": ad_credit_days if ad else None,
                "actual_grn_date": item_grn_date,
                "ad_due_date": (
                    add_days(item_grn_date, ad_credit_days) if (item_grn_date and ad) else None
                ),
                "quality_status": grn.get("quality_status"),
                "actual_received_qty": flt(i.received_qty),
                "ad_pending_qty": item_pending,
                "ad_amount": item_ad if ad else None,
                "ad_paid": flt(item_ad * ad_paid_ratio, 2) if ad else None,
                "ad_request_date": ad.get("request_date") if ad else None,
                "ad_paid_date": ad.get("paid_date") if ad else None,
                "od_term": od.get("payment_term") if od else None,
                # On Delivery payment due date = Actual GRN Date
                "od_due_date": item_grn_date,
                "od_amount": item_od if od else None,
                "od_paid": flt(item_od * od_paid_ratio, 2) if od else None,
                "od_request_date": od.get("request_date") if od else None,
                "od_paid_date": od.get("paid_date") if od else None,
            })

            # Payment Request entries of this item, in the PO's column order
            for pr_name, pr_qty in item_entries:
                n = bd_entry_no[pr_name]
                data[-1]["bd_pr_{0}".format(n)] = pr_name
                data[-1]["bd_qty_{0}".format(n)] = pr_qty

    return data